// Wrapper header for bindgen to pull in the public GGML API.
#include "ggml.h"
#include "ggml-alloc.h"
#include "ggml-backend.h"
#include "ggml-blas.h"
#include "ggml-cann.h"
#include "ggml-cpu.h"
#include "ggml-cuda.h"
#include "ggml-metal.h"
#include "ggml-opencl.h"
#include "ggml-opt.h"
#include "ggml-rpc.h"
#include "ggml-sycl.h"
#include "ggml-vulkan.h"
#include "ggml-webgpu.h"
#include "gguf.h"
