#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(non_snake_case)]

#![doc = concat!(
    "Build Info\n\n",
    "- GGML Commit: ", env!("GGML_FFI_GGML_COMMIT"), "\n",
    "- GGML Commit Time: ", env!("GGML_FFI_GGML_COMMIT_TIME"), "\n\n",
    "---\n\n",
    include_str!("../README.md")
)]

// Low-level FFI bindings generated by bindgen live here.
// Build script emits the correct link flags for ggml and backends.
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

/// ggml submodule commit (short hash).
pub const GGML_COMMIT: &str = env!("GGML_FFI_GGML_COMMIT");
/// ggml submodule commit time (ISO 8601 or fallback).
pub const GGML_COMMIT_TIME: &str = env!("GGML_FFI_GGML_COMMIT_TIME");
