#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(non_snake_case)]

// Low-level FFI bindings generated by bindgen live here.
// Build script emits the correct link flags for ggml and backends.
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
