name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.3
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}
